

services:
  iris-fhir:
    build: .
    container_name: iris-fhir
    restart: unless-stopped
    ports:
      - "32783:52773"  # Map local port 32783 to IRIS web port 52773
      - "32782:1972"  # Map local port 32782 to iris for health superserver port 1972
    volumes:
      - ./data:/data  # Map local 'data' directory to '/data' inside container
    environment:
      ISC_DATA_DIRECTORY: /data/ifconfig
      ISC_CPF_MERGE_FILE: /merge/CMF.cpf
    entrypoint: ["/iris-main"]